# Generated by Django 4.0.4 on 2022-04-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sender',
            new_name='author',
        ),
    ]
